version: '3'
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rkdskdzhd
      MYSQL_DATABASE: nangkongAPI
      DB_USER: root
      DB_PASSWORD: rkdskdzhd
      DB_NAME: nangkongAPI
    ports:
      - "3308:3306"
    volumes:
      - ./data:/var/lib/mysql
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db